// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"demo-go/app/controller/user_controller"
	"demo-go/app/dao/product_dao"
	"demo-go/app/dao/user_dao"
	"demo-go/app/service/user_service"
)

// Injectors from provider.go:

// InitializeUserController 自动生成构造函数
func InitializeUserController() (*user_controller.Controller, error) {
	dao := user_dao.NewDao()
	product_daoDao := product_dao.NewDao()
	service := user_service.NewService(dao, product_daoDao)
	controller := user_controller.NewController(service)
	return controller, nil
}
